export interface City {
  slug: string;
  name: string;
  country: string;
  lat: number;
  lng: number;
  description: string;
  landmarks: string[];
  sizeLabel: string;
  continent: string;
}

export const cities: City[] = [
  // North America - Major Cities
  { slug: "new-york", name: "New York City", country: "United States", lat: 40.7128, lng: -74.006, description: "Explore Manhattan's iconic grid, Central Park, and towering skyscrapers recreated block by block from real map data.", landmarks: ["Central Park", "Times Square", "Empire State Building", "Brooklyn Bridge"], sizeLabel: "Large", continent: "North America" },
  { slug: "los-angeles", name: "Los Angeles", country: "United States", lat: 34.0522, lng: -118.2437, description: "From Hollywood Boulevard to the Santa Monica Pier, LA's sprawling urban landscape comes alive in Minecraft.", landmarks: ["Hollywood Boulevard", "Santa Monica Pier", "Griffith Observatory", "Venice Beach"], sizeLabel: "XL", continent: "North America" },
  { slug: "chicago", name: "Chicago", country: "United States", lat: 41.8781, lng: -87.6298, description: "The Windy City's stunning lakefront, deep-dish-worthy downtown, and iconic L train routes in blocky perfection.", landmarks: ["Millennium Park", "Navy Pier", "Willis Tower", "Wrigley Field"], sizeLabel: "Large", continent: "North America" },
  { slug: "san-francisco", name: "San Francisco", country: "United States", lat: 37.7749, lng: -122.4194, description: "Hilly terrain, the Golden Gate Bridge area, and cable car routes make SF one of the most dramatic Minecraft worlds.", landmarks: ["Golden Gate Bridge", "Fisherman's Wharf", "Chinatown", "Alcatraz Island"], sizeLabel: "Medium", continent: "North America" },
  { slug: "washington-dc", name: "Washington D.C.", country: "United States", lat: 38.9072, lng: -77.0369, description: "The National Mall, Capitol Building, and White House neighborhood faithfully converted from real-world map data.", landmarks: ["National Mall", "Capitol Building", "White House", "Lincoln Memorial"], sizeLabel: "Medium", continent: "North America" },
  { slug: "miami", name: "Miami", country: "United States", lat: 25.7617, lng: -80.1918, description: "South Beach, the Art Deco Historic District, and Biscayne Bay's waterfront transformed into a tropical Minecraft world.", landmarks: ["South Beach", "Brickell", "Wynwood", "Key Biscayne"], sizeLabel: "Large", continent: "North America" },
  { slug: "seattle", name: "Seattle", country: "United States", lat: 47.6062, lng: -122.3321, description: "The Space Needle neighborhood, Pike Place Market area, and Puget Sound waterfront in Minecraft blocks.", landmarks: ["Space Needle", "Pike Place Market", "Capitol Hill", "Pioneer Square"], sizeLabel: "Medium", continent: "North America" },
  { slug: "boston", name: "Boston", country: "United States", lat: 42.3601, lng: -71.0589, description: "Walk the Freedom Trail through America's oldest neighborhoods, now recreated as a Minecraft world.", landmarks: ["Boston Common", "Fenway Park", "Harvard Square", "Faneuil Hall"], sizeLabel: "Medium", continent: "North America" },
  { slug: "denver", name: "Denver", country: "United States", lat: 39.7392, lng: -104.9903, description: "The Mile High City's downtown grid and mountain-adjacent terrain make for a unique Minecraft landscape.", landmarks: ["Union Station", "Coors Field", "State Capitol", "16th Street Mall"], sizeLabel: "Medium", continent: "North America" },
  { slug: "austin", name: "Austin", country: "United States", lat: 30.2672, lng: -97.7431, description: "Keep Austin Weird in Minecraft — the Capitol, Lady Bird Lake, and South Congress all in block form.", landmarks: ["State Capitol", "Lady Bird Lake", "6th Street", "South Congress"], sizeLabel: "Medium", continent: "North America" },
  { slug: "nashville", name: "Nashville", country: "United States", lat: 36.1627, lng: -86.7816, description: "Music City's Broadway honky-tonks, the Parthenon replica, and Cumberland River in Minecraft.", landmarks: ["Broadway", "Ryman Auditorium", "Parthenon", "Nissan Stadium"], sizeLabel: "Medium", continent: "North America" },
  { slug: "portland", name: "Portland", country: "United States", lat: 45.5152, lng: -122.6784, description: "Portland's bridges, food cart districts, and tree-lined neighborhoods converted to Minecraft blocks.", landmarks: ["Pioneer Courthouse Square", "Hawthorne Bridge", "Pearl District", "Forest Park"], sizeLabel: "Medium", continent: "North America" },
  { slug: "philadelphia", name: "Philadelphia", country: "United States", lat: 39.9526, lng: -75.1652, description: "Philly's historic district, the Art Museum steps, and South Street now explorable in Minecraft.", landmarks: ["Independence Hall", "Art Museum", "Rittenhouse Square", "South Street"], sizeLabel: "Large", continent: "North America" },
  { slug: "atlanta", name: "Atlanta", country: "United States", lat: 33.749, lng: -84.388, description: "Peachtree Street, Centennial Olympic Park, and the Atlanta skyline in blocky detail.", landmarks: ["Centennial Olympic Park", "Georgia Aquarium", "Midtown", "Buckhead"], sizeLabel: "Large", continent: "North America" },
  { slug: "new-orleans", name: "New Orleans", country: "United States", lat: 29.9511, lng: -90.0715, description: "The French Quarter's narrow streets, Jackson Square, and Mississippi River waterfront in Minecraft.", landmarks: ["French Quarter", "Jackson Square", "Bourbon Street", "Garden District"], sizeLabel: "Medium", continent: "North America" },
  { slug: "las-vegas", name: "Las Vegas", country: "United States", lat: 36.1699, lng: -115.1398, description: "The Strip's mega-structures, casinos, and desert surroundings make for an unforgettable Minecraft world.", landmarks: ["The Strip", "Fremont Street", "Bellagio", "Downtown"], sizeLabel: "Large", continent: "North America" },
  { slug: "san-diego", name: "San Diego", country: "United States", lat: 32.7157, lng: -117.1611, description: "Balboa Park, the Gaslamp Quarter, and Pacific coastline recreated in Minecraft.", landmarks: ["Balboa Park", "Gaslamp Quarter", "Coronado", "La Jolla"], sizeLabel: "Large", continent: "North America" },
  { slug: "minneapolis", name: "Minneapolis", country: "United States", lat: 44.9778, lng: -93.265, description: "The City of Lakes with its downtown skyways and Mississippi riverfront in Minecraft form.", landmarks: ["Nicollet Mall", "Stone Arch Bridge", "Lake Calhoun", "US Bank Stadium"], sizeLabel: "Medium", continent: "North America" },
  { slug: "detroit", name: "Detroit", country: "United States", lat: 42.3314, lng: -83.0458, description: "Motor City's renaissance downtown, riverfront, and iconic architecture in Minecraft blocks.", landmarks: ["Campus Martius", "Renaissance Center", "Belle Isle", "Corktown"], sizeLabel: "Large", continent: "North America" },
  { slug: "honolulu", name: "Honolulu", country: "United States", lat: 21.3069, lng: -157.8583, description: "Waikiki Beach, Diamond Head, and Honolulu's coastal city grid as a tropical Minecraft world.", landmarks: ["Waikiki Beach", "Diamond Head", "Pearl Harbor", "Iolani Palace"], sizeLabel: "Medium", continent: "North America" },
  { slug: "toronto", name: "Toronto", country: "Canada", lat: 43.6532, lng: -79.3832, description: "Canada's largest city with the CN Tower neighborhood, waterfront, and diverse districts in Minecraft.", landmarks: ["CN Tower", "Distillery District", "Kensington Market", "Royal Ontario Museum"], sizeLabel: "Large", continent: "North America" },
  { slug: "vancouver", name: "Vancouver", country: "Canada", lat: 49.2827, lng: -123.1207, description: "Stanley Park, the seawall, and Vancouver's stunning mountain-meets-ocean setting in Minecraft.", landmarks: ["Stanley Park", "Gastown", "Granville Island", "English Bay"], sizeLabel: "Medium", continent: "North America" },
  { slug: "mexico-city", name: "Mexico City", country: "Mexico", lat: 19.4326, lng: -99.1332, description: "The Zócalo, Chapultepec, and Paseo de la Reforma — one of the world's largest cities in Minecraft.", landmarks: ["Zócalo", "Chapultepec Castle", "Paseo de la Reforma", "Coyoacán"], sizeLabel: "XL", continent: "North America" },

  // Europe
  { slug: "london", name: "London", country: "United Kingdom", lat: 51.5074, lng: -0.1278, description: "Big Ben, the Thames, Buckingham Palace, and London's winding medieval streets in Minecraft.", landmarks: ["Big Ben", "Tower Bridge", "Buckingham Palace", "Hyde Park"], sizeLabel: "XL", continent: "Europe" },
  { slug: "paris", name: "Paris", country: "France", lat: 48.8566, lng: 2.3522, description: "The City of Light with the Eiffel Tower area, Champs-Élysées, and Seine River banks in block form.", landmarks: ["Eiffel Tower", "Champs-Élysées", "Notre-Dame", "Louvre"], sizeLabel: "Large", continent: "Europe" },
  { slug: "rome", name: "Rome", country: "Italy", lat: 41.9028, lng: 12.4964, description: "The Eternal City's ancient street layout, piazzas, and seven hills recreated in Minecraft.", landmarks: ["Colosseum", "Vatican", "Trevi Fountain", "Pantheon"], sizeLabel: "Large", continent: "Europe" },
  { slug: "barcelona", name: "Barcelona", country: "Spain", lat: 41.3874, lng: 2.1686, description: "Gaudí's grid, Las Ramblas, and the Gothic Quarter — Barcelona's unique urban form in Minecraft.", landmarks: ["Sagrada Família", "Las Ramblas", "Park Güell", "Gothic Quarter"], sizeLabel: "Large", continent: "Europe" },
  { slug: "amsterdam", name: "Amsterdam", country: "Netherlands", lat: 52.3676, lng: 4.9041, description: "Amsterdam's iconic canal rings, narrow houses, and cycling infrastructure faithfully converted.", landmarks: ["Canal Ring", "Dam Square", "Vondelpark", "Rijksmuseum area"], sizeLabel: "Medium", continent: "Europe" },
  { slug: "berlin", name: "Berlin", country: "Germany", lat: 52.52, lng: 13.405, description: "The Brandenburg Gate area, Tiergarten, and Berlin's wide boulevards in Minecraft.", landmarks: ["Brandenburg Gate", "Tiergarten", "Alexanderplatz", "Reichstag"], sizeLabel: "XL", continent: "Europe" },
  { slug: "vienna", name: "Vienna", country: "Austria", lat: 48.2082, lng: 16.3738, description: "The Ringstraße, Schönbrunn area, and Vienna's imperial architecture in blocky grandeur.", landmarks: ["Ringstraße", "St. Stephen's Cathedral", "Schönbrunn", "Prater"], sizeLabel: "Large", continent: "Europe" },
  { slug: "prague", name: "Prague", country: "Czech Republic", lat: 50.0755, lng: 14.4378, description: "The Charles Bridge, Old Town Square, and Prague Castle hill in Minecraft — a fairytale cityscape.", landmarks: ["Charles Bridge", "Old Town Square", "Prague Castle", "Wenceslas Square"], sizeLabel: "Medium", continent: "Europe" },
  { slug: "lisbon", name: "Lisbon", country: "Portugal", lat: 38.7223, lng: -9.1393, description: "Lisbon's dramatic hills, colorful Alfama district, and Tagus River waterfront in Minecraft.", landmarks: ["Belém Tower", "Alfama", "Praça do Comércio", "Bairro Alto"], sizeLabel: "Medium", continent: "Europe" },
  { slug: "copenhagen", name: "Copenhagen", country: "Denmark", lat: 55.6761, lng: 12.5683, description: "Nyhavn, Tivoli Gardens area, and Copenhagen's cycling-friendly streets in Minecraft blocks.", landmarks: ["Nyhavn", "Tivoli Gardens", "Little Mermaid", "Strøget"], sizeLabel: "Medium", continent: "Europe" },
  { slug: "stockholm", name: "Stockholm", country: "Sweden", lat: 59.3293, lng: 18.0686, description: "Stockholm's island archipelago, Gamla Stan, and waterfront views converted to Minecraft.", landmarks: ["Gamla Stan", "Djurgården", "City Hall", "Södermalm"], sizeLabel: "Medium", continent: "Europe" },
  { slug: "dublin", name: "Dublin", country: "Ireland", lat: 53.3498, lng: -6.2603, description: "Temple Bar, the River Liffey, and Dublin's Georgian architecture in Minecraft form.", landmarks: ["Temple Bar", "Trinity College", "Phoenix Park", "Grafton Street"], sizeLabel: "Medium", continent: "Europe" },
  { slug: "edinburgh", name: "Edinburgh", country: "United Kingdom", lat: 55.9533, lng: -3.1883, description: "Edinburgh Castle, the Royal Mile, and Arthur's Seat — dramatic terrain meets medieval streets.", landmarks: ["Edinburgh Castle", "Royal Mile", "Arthur's Seat", "Princes Street"], sizeLabel: "Medium", continent: "Europe" },
  { slug: "munich", name: "Munich", country: "Germany", lat: 48.1351, lng: 11.582, description: "Marienplatz, the English Garden, and Munich's Bavarian architecture in Minecraft.", landmarks: ["Marienplatz", "English Garden", "Olympiapark", "Allianz Arena area"], sizeLabel: "Large", continent: "Europe" },
  { slug: "florence", name: "Florence", country: "Italy", lat: 43.7696, lng: 11.2558, description: "The Duomo, Ponte Vecchio, and Renaissance Florence's compact historic center in Minecraft.", landmarks: ["Duomo", "Ponte Vecchio", "Uffizi area", "Piazza della Signoria"], sizeLabel: "Small", continent: "Europe" },
  { slug: "istanbul", name: "Istanbul", country: "Turkey", lat: 41.0082, lng: 28.9784, description: "Where Europe meets Asia — the Bosphorus, Hagia Sophia area, and Grand Bazaar district in Minecraft.", landmarks: ["Hagia Sophia", "Blue Mosque", "Grand Bazaar", "Galata Tower"], sizeLabel: "XL", continent: "Europe" },
  { slug: "athens", name: "Athens", country: "Greece", lat: 37.9838, lng: 23.7275, description: "The Acropolis hill, Plaka district, and Athens' ancient-meets-modern cityscape in Minecraft.", landmarks: ["Acropolis", "Plaka", "Syntagma Square", "Temple of Zeus"], sizeLabel: "Medium", continent: "Europe" },
  { slug: "moscow", name: "Moscow", country: "Russia", lat: 55.7558, lng: 37.6173, description: "Red Square, the Kremlin walls, and Moscow's grand boulevards recreated in Minecraft.", landmarks: ["Red Square", "Kremlin", "St. Basil's Cathedral", "Gorky Park"], sizeLabel: "XL", continent: "Europe" },
  { slug: "zurich", name: "Zurich", country: "Switzerland", lat: 47.3769, lng: 8.5417, description: "Zurich's Old Town, lakefront, and Alpine-adjacent cityscape in precise Minecraft blocks.", landmarks: ["Bahnhofstrasse", "Old Town", "Lake Zurich", "Grossmünster"], sizeLabel: "Medium", continent: "Europe" },

  // Asia
  { slug: "tokyo", name: "Tokyo", country: "Japan", lat: 35.6762, lng: 139.6503, description: "Shibuya crossing, Shinjuku towers, and Tokyo's dense urban fabric — a Minecraft megacity.", landmarks: ["Shibuya Crossing", "Shinjuku", "Tokyo Tower", "Asakusa"], sizeLabel: "XL", continent: "Asia" },
  { slug: "singapore", name: "Singapore", country: "Singapore", lat: 1.3521, lng: 103.8198, description: "Marina Bay, Gardens by the Bay area, and Singapore's futuristic skyline in Minecraft.", landmarks: ["Marina Bay Sands area", "Gardens by the Bay", "Chinatown", "Orchard Road"], sizeLabel: "Large", continent: "Asia" },
  { slug: "seoul", name: "Seoul", country: "South Korea", lat: 37.5665, lng: 126.978, description: "Gangnam, Myeongdong, and the Han River — Seoul's dynamic cityscape in Minecraft form.", landmarks: ["Gyeongbokgung area", "Gangnam", "Myeongdong", "Bukchon Hanok Village"], sizeLabel: "XL", continent: "Asia" },
  { slug: "dubai", name: "Dubai", country: "UAE", lat: 25.2048, lng: 55.2708, description: "The Burj Khalifa neighborhood, Palm Jumeirah coastline, and Dubai's superlative skyline in Minecraft.", landmarks: ["Burj Khalifa area", "Dubai Marina", "Old Dubai", "Palm Jumeirah"], sizeLabel: "XL", continent: "Asia" },
  { slug: "bangkok", name: "Bangkok", country: "Thailand", lat: 13.7563, lng: 100.5018, description: "Grand Palace area, Chao Phraya River, and Bangkok's vibrant street grid in Minecraft.", landmarks: ["Grand Palace area", "Khao San Road", "Chatuchak", "Chinatown"], sizeLabel: "XL", continent: "Asia" },
  { slug: "hong-kong", name: "Hong Kong", country: "China", lat: 22.3193, lng: 114.1694, description: "Victoria Harbour, dense high-rises, and Hong Kong's dramatic hillside cityscape in Minecraft.", landmarks: ["Victoria Harbour", "Central", "Tsim Sha Tsui", "The Peak area"], sizeLabel: "Large", continent: "Asia" },
  { slug: "kyoto", name: "Kyoto", country: "Japan", lat: 35.0116, lng: 135.7681, description: "Ancient temples, traditional machiya streets, and Kyoto's historic grid in Minecraft blocks.", landmarks: ["Kinkaku-ji area", "Fushimi Inari", "Gion", "Arashiyama"], sizeLabel: "Large", continent: "Asia" },
  { slug: "mumbai", name: "Mumbai", country: "India", lat: 19.076, lng: 72.8777, description: "Gateway of India area, Marine Drive, and Mumbai's bustling peninsula in Minecraft.", landmarks: ["Gateway of India", "Marine Drive", "Colaba", "Bandra"], sizeLabel: "XL", continent: "Asia" },
  { slug: "beijing", name: "Beijing", country: "China", lat: 39.9042, lng: 116.4074, description: "The Forbidden City, Tiananmen Square area, and Beijing's ring road system in Minecraft.", landmarks: ["Forbidden City", "Tiananmen Square", "Temple of Heaven", "Hutongs"], sizeLabel: "XL", continent: "Asia" },
  { slug: "taipei", name: "Taipei", country: "Taiwan", lat: 25.033, lng: 121.5654, description: "Taipei 101 neighborhood, night market districts, and riverside parks in Minecraft.", landmarks: ["Taipei 101 area", "Ximending", "Shilin Night Market area", "Longshan Temple"], sizeLabel: "Large", continent: "Asia" },
  { slug: "hanoi", name: "Hanoi", country: "Vietnam", lat: 21.0285, lng: 105.8542, description: "The Old Quarter's 36 streets, Hoàn Kiếm Lake, and French colonial architecture in Minecraft.", landmarks: ["Old Quarter", "Hoàn Kiếm Lake", "Temple of Literature", "West Lake"], sizeLabel: "Medium", continent: "Asia" },
  { slug: "jerusalem", name: "Jerusalem", country: "Israel", lat: 31.7683, lng: 35.2137, description: "The Old City's four quarters, the Western Wall area, and ancient streets in Minecraft.", landmarks: ["Old City", "Western Wall area", "Mount of Olives", "Via Dolorosa"], sizeLabel: "Medium", continent: "Asia" },

  // Oceania
  { slug: "sydney", name: "Sydney", country: "Australia", lat: -33.8688, lng: 151.2093, description: "The Opera House harbor, Harbour Bridge area, and Sydney's stunning coastline in Minecraft.", landmarks: ["Opera House area", "Harbour Bridge", "Darling Harbour", "Bondi Beach"], sizeLabel: "Large", continent: "Oceania" },
  { slug: "melbourne", name: "Melbourne", country: "Australia", lat: -37.8136, lng: 144.9631, description: "Melbourne's laneways, Yarra River, and cultural districts converted to Minecraft blocks.", landmarks: ["Federation Square", "Flinders Street", "Yarra River", "St Kilda"], sizeLabel: "Large", continent: "Oceania" },
  { slug: "auckland", name: "Auckland", country: "New Zealand", lat: -36.8485, lng: 174.7633, description: "City of Sails — Auckland's harbour, Sky Tower area, and volcanic cones in Minecraft.", landmarks: ["Sky Tower area", "Viaduct Harbour", "Mission Bay", "Mount Eden"], sizeLabel: "Medium", continent: "Oceania" },

  // South America
  { slug: "rio-de-janeiro", name: "Rio de Janeiro", country: "Brazil", lat: -22.9068, lng: -43.1729, description: "Copacabana, Sugarloaf area, and Rio's dramatic mountain-meets-beach terrain in Minecraft.", landmarks: ["Copacabana", "Sugarloaf area", "Ipanema", "Centro"], sizeLabel: "XL", continent: "South America" },
  { slug: "buenos-aires", name: "Buenos Aires", country: "Argentina", lat: -34.6037, lng: -58.3816, description: "La Boca, Puerto Madero, and Buenos Aires' wide European-style avenues in Minecraft.", landmarks: ["La Boca", "Puerto Madero", "Recoleta", "San Telmo"], sizeLabel: "XL", continent: "South America" },
  { slug: "bogota", name: "Bogotá", country: "Colombia", lat: 4.711, lng: -74.0721, description: "La Candelaria, Monserrate area, and Bogotá's highland cityscape in Minecraft blocks.", landmarks: ["La Candelaria", "Monserrate area", "Zona T", "Usaquén"], sizeLabel: "Large", continent: "South America" },
  { slug: "lima", name: "Lima", country: "Peru", lat: -12.0464, lng: -77.0428, description: "Miraflores cliffs, the historic center, and Lima's Pacific coastline in Minecraft.", landmarks: ["Miraflores", "Historic Center", "Barranco", "San Isidro"], sizeLabel: "Large", continent: "South America" },
  { slug: "santiago", name: "Santiago", country: "Chile", lat: -33.4489, lng: -70.6693, description: "Santiago's grid with the Andes backdrop, Providencia, and Bellavista in Minecraft.", landmarks: ["Plaza de Armas", "Providencia", "Bellavista", "Santa Lucía Hill"], sizeLabel: "Large", continent: "South America" },

  // Africa
  { slug: "cairo", name: "Cairo", country: "Egypt", lat: 30.0444, lng: 31.2357, description: "The Nile riverbanks, Islamic Cairo's labyrinthine streets, and the Giza plateau area in Minecraft.", landmarks: ["Tahrir Square", "Khan el-Khalili", "Nile Corniche", "Giza area"], sizeLabel: "XL", continent: "Africa" },
  { slug: "cape-town", name: "Cape Town", country: "South Africa", lat: -33.9249, lng: 18.4241, description: "Table Mountain area, the V&A Waterfront, and Cape Town's coastal beauty in Minecraft.", landmarks: ["V&A Waterfront", "Table Mountain area", "Bo-Kaap", "Long Street"], sizeLabel: "Large", continent: "Africa" },
  { slug: "marrakech", name: "Marrakech", country: "Morocco", lat: 31.6295, lng: -7.9811, description: "The Medina, Jemaa el-Fnaa square, and Marrakech's ancient walled city in Minecraft blocks.", landmarks: ["Jemaa el-Fnaa", "Medina", "Majorelle Garden area", "Bahia Palace area"], sizeLabel: "Medium", continent: "Africa" },
  { slug: "nairobi", name: "Nairobi", country: "Kenya", lat: -1.2921, lng: 36.8219, description: "Kenya's capital with its central business district and Uhuru Park area in Minecraft.", landmarks: ["CBD", "Uhuru Park", "Westlands", "Karen"], sizeLabel: "Large", continent: "Africa" },

  // US State Capitals
  { slug: "sacramento", name: "Sacramento", country: "United States", lat: 38.5816, lng: -121.4944, description: "California's capital with its tree-lined grid, Capitol Park, and Old Sacramento waterfront.", landmarks: ["State Capitol", "Old Sacramento", "Capitol Park", "Midtown"], sizeLabel: "Medium", continent: "North America" },
  { slug: "albany", name: "Albany", country: "United States", lat: 42.6526, lng: -73.7562, description: "New York's capital with the Empire State Plaza and Hudson River setting in Minecraft.", landmarks: ["Empire State Plaza", "State Capitol", "Washington Park", "Lark Street"], sizeLabel: "Small", continent: "North America" },
  { slug: "tallahassee", name: "Tallahassee", country: "United States", lat: 30.4383, lng: -84.2807, description: "Florida's capital with its rolling hills, university campus areas, and Capitol complex.", landmarks: ["State Capitol", "FSU Campus", "Cascades Park", "Railroad Square"], sizeLabel: "Medium", continent: "North America" },
  { slug: "columbus", name: "Columbus", country: "United States", lat: 39.9612, lng: -82.9988, description: "Ohio's capital with the Short North, Scioto Mile, and OSU campus area in Minecraft.", landmarks: ["Short North", "Scioto Mile", "German Village", "Ohio State campus"], sizeLabel: "Large", continent: "North America" },
  { slug: "raleigh", name: "Raleigh", country: "United States", lat: 35.7796, lng: -78.6382, description: "North Carolina's capital — the City of Oaks with its tree-covered downtown in Minecraft.", landmarks: ["State Capitol", "Fayetteville Street", "NC State area", "Moore Square"], sizeLabel: "Medium", continent: "North America" },
  { slug: "madison", name: "Madison", country: "United States", lat: 43.0731, lng: -89.4012, description: "Wisconsin's capital on an isthmus between two lakes — a unique geography for Minecraft.", landmarks: ["State Capitol", "State Street", "UW Campus", "Lake Mendota shore"], sizeLabel: "Medium", continent: "North America" },
  { slug: "salt-lake-city", name: "Salt Lake City", country: "United States", lat: 40.7608, lng: -111.891, description: "Utah's capital with its mountain backdrop, wide streets, and Temple Square area.", landmarks: ["Temple Square", "State Capitol", "City Creek", "Liberty Park"], sizeLabel: "Medium", continent: "North America" },
  { slug: "boise", name: "Boise", country: "United States", lat: 43.615, lng: -116.2023, description: "Idaho's capital with the Boise River Greenbelt and downtown district in Minecraft.", landmarks: ["State Capitol", "Boise River Greenbelt", "Basque Block", "8th Street"], sizeLabel: "Medium", continent: "North America" },
  { slug: "richmond", name: "Richmond", country: "United States", lat: 37.5407, lng: -77.436, description: "Virginia's capital with the James River, Carytown, and historic Fan District in Minecraft.", landmarks: ["State Capitol", "Carytown", "Fan District", "Shockoe Bottom"], sizeLabel: "Medium", continent: "North America" },
  { slug: "annapolis", name: "Annapolis", country: "United States", lat: 38.9784, lng: -76.4922, description: "Maryland's capital — a charming colonial harbor town perfect for a small Minecraft world.", landmarks: ["State House", "City Dock", "Naval Academy area", "Main Street"], sizeLabel: "Small", continent: "North America" },
  { slug: "charleston", name: "Charleston", country: "United States", lat: 32.7765, lng: -79.9311, description: "Historic Charleston's pastel row houses, harbor, and cobblestone streets in Minecraft.", landmarks: ["Battery", "Rainbow Row", "King Street", "Waterfront Park"], sizeLabel: "Small", continent: "North America" },
  { slug: "savannah", name: "Savannah", country: "United States", lat: 32.0809, lng: -81.0912, description: "Savannah's iconic squares, tree-lined streets, and River Street waterfront in Minecraft.", landmarks: ["Forsyth Park", "River Street", "Historic squares", "City Market"], sizeLabel: "Small", continent: "North America" },

  // University Towns
  { slug: "cambridge-ma", name: "Cambridge", country: "United States", lat: 42.3736, lng: -71.1097, description: "Home to Harvard and MIT — explore the campuses and Harvard Square in Minecraft.", landmarks: ["Harvard Yard", "MIT Campus", "Harvard Square", "Central Square"], sizeLabel: "Medium", continent: "North America" },
  { slug: "oxford", name: "Oxford", country: "United Kingdom", lat: 51.752, lng: -1.2577, description: "Oxford's dreaming spires, college quads, and the Bodleian Library area in Minecraft.", landmarks: ["Bodleian Library area", "Christ Church", "Radcliffe Camera area", "High Street"], sizeLabel: "Small", continent: "Europe" },

  // Popular Landmarks / Unique Cities
  { slug: "venice", name: "Venice", country: "Italy", lat: 45.4408, lng: 12.3155, description: "Venice's canals, bridges, and car-free island layout make it one of the most unique Minecraft worlds possible.", landmarks: ["St. Mark's Square", "Rialto Bridge", "Grand Canal", "Murano"], sizeLabel: "Medium", continent: "Europe" },
  { slug: "monaco", name: "Monaco", country: "Monaco", lat: 43.7384, lng: 7.4246, description: "The entire principality in Minecraft — Monte Carlo, the harbor, and the famous Grand Prix circuit route.", landmarks: ["Monte Carlo Casino area", "Port Hercules", "Prince's Palace", "Grand Prix circuit"], sizeLabel: "Small", continent: "Europe" },
  { slug: "singapore-marina", name: "Marina Bay", country: "Singapore", lat: 1.2839, lng: 103.8607, description: "Singapore's iconic Marina Bay skyline with its futuristic architecture in Minecraft.", landmarks: ["Marina Bay Sands area", "Merlion Park", "Esplanade", "Gardens by the Bay"], sizeLabel: "Small", continent: "Asia" },
  { slug: "dubai-marina", name: "Dubai Marina", country: "UAE", lat: 25.08, lng: 55.1408, description: "Dubai Marina's towering residential skyline and waterfront promenade in Minecraft.", landmarks: ["Marina Walk", "JBR Beach", "Marina Mall area", "Ain Dubai area"], sizeLabel: "Small", continent: "Asia" },
  { slug: "manhattan", name: "Manhattan", country: "United States", lat: 40.7831, lng: -73.9712, description: "The heart of New York — Midtown's skyscrapers, Central Park, and the Village in Minecraft.", landmarks: ["Midtown", "Central Park", "Wall Street area", "Greenwich Village"], sizeLabel: "Large", continent: "North America" },
  { slug: "san-juan", name: "San Juan", country: "Puerto Rico", lat: 18.4655, lng: -66.1057, description: "Old San Juan's colorful colonial streets, El Morro fort area, and Caribbean waterfront.", landmarks: ["Old San Juan", "El Morro area", "Condado", "La Fortaleza"], sizeLabel: "Small", continent: "North America" },
  { slug: "havana", name: "Havana", country: "Cuba", lat: 23.1136, lng: -82.3666, description: "Havana's crumbling colonial grandeur, the Malecón, and Old Havana's plazas in Minecraft.", landmarks: ["Old Havana", "Malecón", "Capitolio area", "Plaza Vieja"], sizeLabel: "Medium", continent: "North America" },
  { slug: "petra", name: "Petra Area", country: "Jordan", lat: 30.3285, lng: 35.4444, description: "The ancient rose city's surrounding terrain and Wadi Musa town in Minecraft.", landmarks: ["Wadi Musa", "Petra entrance area", "Mountain terrain", "Valley landscape"], sizeLabel: "Medium", continent: "Asia" },
  { slug: "reykjavik", name: "Reykjavik", country: "Iceland", lat: 64.1466, lng: -21.9426, description: "The world's northernmost capital — colorful rooftops, Hallgrímskirkja area, and harbor.", landmarks: ["Hallgrímskirkja area", "Laugavegur", "Old Harbour", "Harpa area"], sizeLabel: "Small", continent: "Europe" },
  { slug: "kyiv", name: "Kyiv", country: "Ukraine", lat: 50.4501, lng: 30.5234, description: "Khreschatyk Boulevard, Maidan, and the Dnipro riverbanks in Minecraft.", landmarks: ["Khreschatyk", "Maidan", "Podil", "Lavra area"], sizeLabel: "Large", continent: "Europe" },
  { slug: "helsinki", name: "Helsinki", country: "Finland", lat: 60.1699, lng: 24.9384, description: "Helsinki's harbor, Senate Square, and Nordic waterfront architecture in Minecraft.", landmarks: ["Senate Square", "Market Square", "Suomenlinna area", "Design District"], sizeLabel: "Medium", continent: "Europe" },
  { slug: "warsaw", name: "Warsaw", country: "Poland", lat: 52.2297, lng: 21.0122, description: "Warsaw's rebuilt Old Town, Palace of Culture area, and Vistula riverfront in Minecraft.", landmarks: ["Old Town", "Palace of Culture", "Łazienki Park", "Nowy Świat"], sizeLabel: "Large", continent: "Europe" },
  { slug: "osaka", name: "Osaka", country: "Japan", lat: 34.6937, lng: 135.5023, description: "Dotonbori, Osaka Castle area, and the neon-lit streets of Japan's kitchen in Minecraft.", landmarks: ["Dotonbori", "Osaka Castle area", "Shinsekai", "Umeda"], sizeLabel: "XL", continent: "Asia" },
  { slug: "kuala-lumpur", name: "Kuala Lumpur", country: "Malaysia", lat: 3.139, lng: 101.6869, description: "The Petronas Towers neighborhood, Batu Caves area, and KL's diverse districts in Minecraft.", landmarks: ["Petronas Towers area", "Merdeka Square", "Bukit Bintang", "Batu Caves area"], sizeLabel: "Large", continent: "Asia" },
  { slug: "buenos-aires-recoleta", name: "Recoleta", country: "Argentina", lat: -34.5875, lng: -58.3933, description: "Buenos Aires' elegant Recoleta neighborhood with its Parisian-style architecture in Minecraft.", landmarks: ["Recoleta Cemetery area", "National Library", "Plaza Francia", "Avenida Alvear"], sizeLabel: "Small", continent: "South America" },
];

export function getCityBySlug(slug: string): City | undefined {
  return cities.find((c) => c.slug === slug);
}

export function getCitiesByContinent(continent: string): City[] {
  return cities.filter((c) => c.continent === continent);
}

export const continents = [...new Set(cities.map((c) => c.continent))];
